- job:
    name: my-job
    project-type: freestyle
    description: My Jenkins job
    disabled: false
    scm:
      - git:
          url: https://github.com/degull20/demo-robotframework.git
          branches:
            - main
          skip-tag: true
    triggers:
      - pollscm:
          cron: "H/2 * * * *"
    builders:
      - shell: |
          echo "Hello, World!"
    publishers:
      - junit:
          test-results: "**/test-results/*.xml"