
- job:
    name: my-robot-test-job
    project-type: freestyle
    description: My Robot Test Job
    disabled: false
    scm:
      - git:
          url: https://github.com/degull20/demo-robotframework.git
          branches:
            - master
    triggers:
      - pollscm:
          cron: "H/2 * * * *"
    builders:
      - shell: |
          pip install -U robotframework
          for file in tests/*.robot; do
            robot --outputdir robot-results "$file"
          done
    publishers:
      - junit:
          test-results: "**/robot-results/*.xml"
