- job:
    name: my-robot-test-job
    project-type: freestyle
    description: My Robot Test Job
    disabled: false
    scm:
      - git:
          url: https://github.com/degull20/demo-robotframework.git
          branches:
            - master
    triggers:
      - pollscm:
          cron: "H/2 * * * *"
    builders:
      - robot:
          requireartifacts: false
          installation: "Robot Framework"
          runcmd: |
            robot --outputdir robot-results my-test-suite.robot
    publishers:
      - junit:
          test-results: "**/robot-results/*.xml"
